### ISSUE TITLE
Update Question 

### ISSUE THREAD

**Issue by modder5555** [Cortex-Modders/CodeLyokoMod#11]
When are you updating this mod to 1.5.2?

**Comment by EnderShadow** [comment]
The github code is updated to 1.5.2 but the forum post will be updated in a few weeks

**Comment by modder5555** [comment]
Ok
I was really excited when I came across your mod, I loved the Code Lyoko Series, Now I'm waiting for Evolution to be in English

**Comment by modder5555** [comment]
I will be excited to play this mod on 1.5.2

**Comment by EnderShadow** [comment]
It always gives me more motivation when people say they like the mod or are looking forward to it. Also, stuff changes between the 1.5.1 version and the 1.5.2 version.

**Comment by modder5555** [comment]
I know, Im looking forward to the marabounta, the tower particle effects, the skid, dimensions, and the console :)

**Comment by modder5555** [comment]
What are the tower colors going to be?

**Comment by EnderShadow** [comment]
Green, red, blue, And if you are a developer, you can make it black.

**Comment by modder5555** [comment]
So Red=Activated
Blue=Neutral
Green=Deactivated
Black=???

**Comment by EnderShadow** [comment]
Red = Activated
Blue = Deactivated
Green = Player Controlled
Black = Developer Mode (only accessible by developers or if you edit the NBT data of the tower)

**Comment by modder5555** [comment]
oh. i thought green was deactivated :3
whoops lol

**Comment by modder5555** [comment]
You should make the scyphozoa :D

**Comment by EnderShadow** [comment]
nope. if you watch some of the episodes where jeremy uses a tower, you'll see the tower is green. I can link you to some of them if you want. I might add the scyphozoa, but probably not.

**Comment by modder5555** [comment]
i always thought dark green was jeremie activated towers

**Comment by modder5555** [comment]
i would like to see though :3

**Comment by EnderShadow** [comment]
you'll see soon enough in the 1.5.2 release. although the towers won't spawn until the "Lyoko Update".

**Comment by jadar** [comment]
maybe i'll add it. ids are there for all the monsters and vehicles.

**Comment by jadar** [comment]
but it wont be needed for a while..

**Comment by modder5555** [comment]
ok, just keep me updated ;P

**Comment by EnderShadow** [comment]
The forum page for the mod should keep you updated. But watching the commits on GitHub will keep you the most up to date.

**Comment by modder5555** [comment]
whats the forum link? :3

**Comment by EnderShadow** [comment]
it's in the mcmod.info file.

**Comment by modder5555** [comment]
ok
