### ISSUE TITLE
One More Question

### ISSUE THREAD

**Issue by modder5555** [Cortex-Modders/CodeLyokoMod#12]
How Do I Use The Portals?

**Comment by EnderShadow** [comment]
They don't work yet. There just blocks at the moment. They'll be useable in the "Lyoko Update" which should be after the 1.5.2 update.

**Comment by modder5555** [comment]
is the 1.5.2 update ready yet?

**Comment by EnderShadow** [comment]
No. But it's almost ready.

**Comment by modder5555** [comment]
great, so im guessin it will be done in about... lets say 3 days maybe? :3

**Comment by EnderShadow** [comment]
probably will be released about then

**Comment by modder5555** [comment]
ok :+1:
