### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by modder5555** [Cortex-Modders/CodeLyokoMod#14]
Can u video ure update with u playing mc. plus the tower. please

**Comment by jadar** [comment]
ya if its ok with endershadow we'll post it here http://www.youtube.com/JadarDev

**Comment by EnderShadow** [comment]
there will also be one on my channel as well. it will be on the mod forum page

**Comment by modder5555** [comment]
tell me when the vid is ready :D

**Comment by modder5555** [comment]
is a video ready yet?

**Comment by EnderShadow** [comment]
The video won't be made until after the release. Just check the forum page everyday or so until it's posted.

**Comment by modder5555** [comment]
k

**Comment by modder5555** [comment]
give an estimate when the 1.5.2 version will be done:3

**Comment by EnderShadow** [comment]
It was just released now. And don't ask about the video. It will be done within a week.

**Comment by modder5555** [comment]
where is it located, 1.5.2 version?

**Comment by EnderShadow** [comment]
Yes

**Comment by modder5555** [comment]
so is it on the forum?

**Comment by EnderShadow** [comment]
Yes

**Comment by modder5555** [comment]
THANK YOU SO MUCH :D XD
:+1:

**Comment by EnderShadow** [comment]
Np

**Comment by modder5555** [comment]
cya later, ill be checking here for updates, later ;P

**Comment by modder5555** [comment]
um what are all the tower codes, I know code xana, and code lyoko, but what are the others?

**Comment by EnderShadow** [comment]
code player is the other one.

**Comment by EnderShadow** [comment]
And then there is a secret developer only code. It won't work unless you are labeled a developer in the code

**Comment by modder5555** [comment]
ok
I noticed the skid is ther now, but how do i use it?

**Comment by EnderShadow** [comment]
None of the vehicles work yet

**Comment by modder5555** [comment]
what about the marabounta, how do i use it

**Comment by modder5555** [comment]
do portals work yet

**Comment by EnderShadow** [comment]
Wait for the video for anything that confuses you

**Comment by modder5555** [comment]
ok ill check next week, or try to figure it out :3

**Comment by modder5555** [comment]
in next update you should add franz hopper effect to the towers

**Comment by EnderShadow** [comment]
the video has been uploaded

**Comment by modder5555** [comment]
So, how is the large update coming along?

**Comment by EnderShadow** [comment]
good so far. But it won't be released till 1.6 then you will know what has been added and what hasn't.

**Comment by modder5555** [comment]
great :D

**Comment by modder5555** [comment]
The 1.6 update is this month, I read it on the forum ;P

**Comment by modder5555** [comment]
Here is a tower review including code developer
Im elementDIVINE

**Comment by modder5555** [comment]
LINK:http://www.youtube.com/watch?v=GeMkePdBrcE

**Comment by modder5555** [comment]
So, How is my video?

**Comment by modder5555** [comment]
what is the 5.0 update,and when is it available?

**Comment by jadar** [comment]
we don't know exactly. im pretty sure lyoko is not ready.

**Comment by jadar** [comment]
also, you can test for us if you want using the experimental jenkins builds that are at http://www.ci.jadarstudios.com/job/Code-Lyoko/

now, could you please take this to the forum post?

**Comment by CLMod** [comment]
Correct but it should be ready soon its just taking me a while because my
finals are coming up really soon

**Comment by EnderShadow** [comment]
Just push to github when you get a chance

**Comment by CLMod** [comment]
Will do

**Comment by modder5555** [comment]
so when is a file going to be updated?
