### ISSUE TITLE
developer codes work for everybody

### ISSUE THREAD

**Issue by jadar** [Cortex-Modders/CodeLyokoMod#15]

**Comment by EnderShadow** [comment]
Are you sure?

**Comment by jadar** [comment]
yeah the modder555 guy used it in his video.

**Comment by modder5555** [comment]
I can edit files for that to happen for me

**Comment by EnderShadow** [comment]
His did you do that?

**Comment by EnderShadow** [comment]
*how

**Comment by modder5555** [comment]
well, also my mc has a custom launcher to where i have any name i want.

**Comment by EnderShadow** [comment]
Oh ok. See! I told you it wasn't broken jadar!

**Comment by modder5555** [comment]
Yup

**Comment by modder5555** [comment]
Sucks, because it is laggy when i enter the tower
:P

**Comment by modder5555** [comment]
Maybe i should remove other mods, that will probably speed it up a bit?

**Comment by EnderShadow** [comment]
Probably. We'll see if we can optimize it

**Comment by modder5555** [comment]
oh yeah, how was the video I made? :D

**Comment by modder5555** [comment]
other than the lag

**Comment by EnderShadow** [comment]
Haven't seen it yet. I'll watch it when i get home

**Comment by modder5555** [comment]
ok

**Comment by CLMod** [comment]
Please move this to the forms...

**Comment by modder5555** [comment]
what mods have you used Shadow?

**Comment by EnderShadow** [comment]
what do you mean?

**Comment by jadar** [comment]
We haven't tested with any other mods yet. The video was ok, thanks. Now since this is not related this issue, please move all talk to the forum post. http://www.minecraftforum.net/topic/1403995-152-code-lyoko-mod-043-minecraft-forum/

**Comment by modder5555** [comment]
i meant what mods do you have on your mc
