### ISSUE TITLE
Scanner instead of portal blocks.

### ISSUE THREAD

**Issue by jadar** [Cortex-Modders/CodeLyokoMod#16]
Hey, I had an idea for going to lyoko. Instead of having a few classes for going to dimensions, wouldn't it be easier to add a virtualize method to the scanner class that targets the nearest player with the same X,Z as the scanner, then teleport him to the dimension passed in as a parameter. This would mean less code for adding new dimensions, remove portal blocks players can spawn in, clean up code, and maybe open up more ways to implement the scanner and it's model/tileentity. it would just need the basic code for teleporting between dimensions and whatnot..

**Comment by CLMod** [comment]
Sounds like a good idea but for now im gonna stick with the portal blocks
this way they will have a way there but I like your idea

**Comment by jadar** [comment]
Well, the scanner might be done in time for us to use to implement it..

**Comment by EnderShadow** [comment]
I have an Idea. what if we have the portal blocks AND use the scanner. that way if we need to go to spawning the portal blocks, we can.

**Comment by jadar** [comment]
I proposed the idea to you.. lol well we could do that but it just seems like extra code to do and not as easily expandable..

**Comment by EnderShadow** [comment]
well, it so we can use portal blocks if the scanners aren't ready

**Comment by jadar** [comment]
well why wouldnt it be ready by the time dimensions are ready?

**Comment by EnderShadow** [comment]
I mean the portal mechanics being in one block.
