### ISSUE TITLE
Mod Testing Question

### ISSUE THREAD

**Issue by modder5555** [Cortex-Modders/CodeLyokoMod#17]
What exactly are the codes for the scanners and/or supercomputer console?

**Comment by EnderShadow** [comment]
The code is just the name of the sector.

**Comment by modder5555** [comment]
ok

**Comment by modder5555** [comment]
its not doing anything. i cant get it to close in the scanner

**Comment by jadar** [comment]
The scanner is not ready yet. I have yet to push my changes, and I'm having some problems which i havent worked out yet. Mainly because of too much Doctor Who..

**Comment by EnderShadow** [comment]
Sorry about the lack of updates. I unknowingly got him into doctor who. My fault :-P

**Comment by modder5555** [comment]
:O, good job, EPIC FAIL, lol

**Comment by jadar** [comment]
Wasn't his fault.. But i did watch 6 episodes yesterday....

**Comment by CLMod** [comment]
DOCTOR WHO IS AMAZING!

On Fri, Jun 7, 2013 at 4:52 PM, jadar notifications@github.com wrote:

> Wasn't his fault.. But i did watch 6 episodes yesterday....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/code-lyoko-modding/CodeLyokoMod/issues/17#issuecomment-19134972
> .

## 

Silver

**Comment by modder5555** [comment]
I play garry's mod, and i have the daleks. THEY ARE IMPOSSIBLE TO DESTROY, THEYRE EVIL O_O

**Comment by EnderShadow** [comment]
The issues tab is for issues or questions and is mainly for the mod authors. It is not for social networking purposes. Please don't make an issue unless it is about the mod.

**Comment by modder5555** [comment]
ok -_-
