### ISSUE TITLE
blocks not appearing

### ISSUE THREAD

**Issue by CLMod** [Cortex-Modders/CodeLyokoMod#5]

**Comment by jadar** [comment]
Dimensions are not ready.. All blocks/items do not have textures yet.. be more specific please.

**Comment by EnderShadow** [comment]
You do know that CLMod is the other programmer. Right?

**Comment by CLMod** [comment]
Dimensions no longer crash its just a matter of getting the blocks to show and do not attempt to fix it as I have a new version on my home computer I just haven't updated it on here yet.

**Comment by jadar** [comment]
has that one been kept up to date with the recent changes? and rendering of which blocks?

**Comment by jadar** [comment]
EnderShadow: yeah lol

**Comment by jadar** [comment]
which blocks don't appear?

**Comment by EnderShadow** [comment]
I think he means for the biome. Because that uses a bye of data do you need to customize it to get blocks over 256 in the world

**Comment by jadar** [comment]
Oh okay.

**Comment by modder5555** [comment]
does this version work for 1.5.2 and 1.6.2? Ive tried it with 1.6.2, and it crashed without any other mod.

**Comment by EnderShadow** [comment]
1.6

**Comment by modder5555** [comment]
it doesnt work for me.

**Comment by modder5555** [comment]
help?

**Comment by EnderShadow** [comment]
I can't trouble shoot it atm

**Comment by modder5555** [comment]
ok
i might tr force updating and reinstalling the mod

**Comment by modder5555** [comment]
try*

**Comment by modder5555** [comment]
what forge version is it
?

**Comment by jadar** [comment]
the latest
