### ISSUE TITLE
Biome Fields.

### ISSUE THREAD

**Issue by jadar** [Cortex-Modders/CodeLyokoMod#8]
Could we change the fields for the Biomes in CodeLyoko.java so that they are not the same as the blocks for them (they are different case.)

**Comment by CLMod** [comment]
what do you mean?

**Comment by jadar** [comment]
The field for the carthage block is LyokoCarthage while the carthage biome is lyokocarthage. It's a bit confusing.

**Comment by CLMod** [comment]
OK

**Comment by jadar** [comment]
Did you do it?

**Comment by CLMod** [comment]
Yes

**Comment by jadar** [comment]
did you push that change?
